"""criando tabelas

Revision ID: 17bc65564f38
Revises: df97d766e8ae
Create Date: 2025-06-17 11:48:30.908238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17bc65564f38'
down_revision = 'df97d766e8ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulacao_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulacao_id', sa.Integer(), nullable=False),
    sa.Column('mes_offset', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['simulacao_id'], ['simulacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulacao_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulacao_id', sa.Integer(), nullable=False),
    sa.Column('pacientes', sa.Integer(), nullable=False),
    sa.Column('valor_sessao', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['simulacao_id'], ['simulacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulacao_itens')
    op.drop_table('simulacao_eventos')
    op.drop_table('simulacoes')
    # ### end Alembic commands ###
