"""Adiciona valor_sessao ao Paciente

Revision ID: 2f1f86d0d101
Revises: 
Create Date: 2025-05-30 12:15:53.757973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f1f86d0d101'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profissao', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('endereco', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('idade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('valor_sessao', sa.Float(), nullable=True))
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=14),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=14),
               nullable=True)
        batch_op.drop_column('valor_sessao')
        batch_op.drop_column('idade')
        batch_op.drop_column('endereco')
        batch_op.drop_column('cep')
        batch_op.drop_column('profissao')

    # ### end Alembic commands ###
