"""Add active field with default

Revision ID: 42441fa8d5de
Revises: a1f902856b97
Create Date: 2025-05-30 16:07:18.413597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42441fa8d5de'
down_revision = 'a1f902856b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(
    sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true())
)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
