"""simulacoes 2

Revision ID: 4ef0f785708d
Revises: 17bc65564f38
Create Date: 2025-06-17 15:30:40.311347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef0f785708d'
down_revision = '17bc65564f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulacoes', sa.Column('despesa_mensal_fixa', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulacoes', 'despesa_mensal_fixa')
    # ### end Alembic commands ###
