"""Add reset_token fields to Usuario

Revision ID: 878bac043bdc
Revises: 4ef0f785708d
Create Date: 2025-06-17 15:56:53.372068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878bac043bdc'
down_revision = '4ef0f785708d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('reset_token', sa.String(length=100), nullable=True))
    op.add_column('usuarios', sa.Column('reset_token_expiration', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'usuarios', ['reset_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'reset_token_expiration')
    op.drop_column('usuarios', 'reset_token')
    # ### end Alembic commands ###
