"""Adiciona coluna data_criacao em transacoes

Revision ID: df97d766e8ae
Revises: 42441fa8d5de
Create Date: 2025-06-11 17:25:01.771538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df97d766e8ae'
down_revision = '42441fa8d5de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_criacao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.drop_column('data_criacao')

    # ### end Alembic commands ###
